-- Run this once in Supabase Dashboard > SQL Editor.
-- Website visitors cannot read or write this table directly.
-- The Next.js server route uses the existing service-role client.

create table if not exists public.click_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id uuid not null,
  event_type text not null check (
    event_type ~ '^[a-z0-9_]+$' and char_length(event_type) <= 60
  ),
  page_path text not null check (char_length(page_path) <= 500),
  page_title text not null default '' check (char_length(page_title) <= 200),
  target_url text check (target_url is null or char_length(target_url) <= 500),
  link_text text not null default '' check (char_length(link_text) <= 160),
  element_type text not null default '' check (char_length(element_type) <= 30),
  element_id text check (element_id is null or char_length(element_id) <= 120),
  referrer text check (referrer is null or char_length(referrer) <= 500),
  utm_source text check (utm_source is null or char_length(utm_source) <= 100),
  utm_medium text check (utm_medium is null or char_length(utm_medium) <= 100),
  utm_campaign text check (
    utm_campaign is null or char_length(utm_campaign) <= 150
  ),
  utm_content text check (
    utm_content is null or char_length(utm_content) <= 150
  ),
  utm_term text check (utm_term is null or char_length(utm_term) <= 150),
  device_type text not null check (
    device_type in ('mobile', 'tablet', 'desktop')
  ),
  browser text not null default '' check (char_length(browser) <= 40),
  screen_width integer not null default 0 check (
    screen_width >= 0 and screen_width <= 10000
  )
);

alter table public.click_events enable row level security;

create index if not exists click_events_created_at_idx
  on public.click_events (created_at desc);

create index if not exists click_events_event_type_idx
  on public.click_events (event_type, created_at desc);

create index if not exists click_events_page_path_idx
  on public.click_events (page_path, created_at desc);

create index if not exists click_events_session_id_idx
  on public.click_events (session_id, created_at desc);

comment on table public.click_events is
  'Privacy-safe website link and button click analytics.';
