-- Run this once in Supabase Dashboard > SQL Editor.
-- Website visitors cannot read or write this table directly.
-- The Next.js server route uses the existing service-role client.

create table if not exists public.click_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id uuid not null,
  visitor_id uuid,
  event_type text not null check (
    event_type ~ '^[a-z0-9_]+$' and char_length(event_type) <= 60
  ),
  page_path text not null check (char_length(page_path) <= 500),
  page_title text not null default '' check (char_length(page_title) <= 200),
  target_url text check (target_url is null or char_length(target_url) <= 500),
  link_text text not null default '' check (char_length(link_text) <= 160),
  element_type text not null default '' check (char_length(element_type) <= 30),
  element_id text check (element_id is null or char_length(element_id) <= 120),
  referrer text check (referrer is null or char_length(referrer) <= 500),
  utm_source text check (utm_source is null or char_length(utm_source) <= 100),
  utm_medium text check (utm_medium is null or char_length(utm_medium) <= 100),
  utm_campaign text check (
    utm_campaign is null or char_length(utm_campaign) <= 150
  ),
  utm_content text check (
    utm_content is null or char_length(utm_content) <= 150
  ),
  utm_term text check (utm_term is null or char_length(utm_term) <= 150),
  device_type text not null check (
    device_type in ('mobile', 'tablet', 'desktop')
  ),
  browser text not null default '' check (char_length(browser) <= 40),
  screen_width integer not null default 0 check (
    screen_width >= 0 and screen_width <= 10000
  ),
  ip_address inet,
  city text check (city is null or char_length(city) <= 120),
  region text check (region is null or char_length(region) <= 120),
  country text check (country is null or char_length(country) = 2),
  traffic_type text not null default 'human' check (
    traffic_type in ('human', 'known_bot', 'suspected_bot')
  ),
  bot_name text check (bot_name is null or char_length(bot_name) <= 80),
  user_agent text check (user_agent is null or char_length(user_agent) <= 500)
);

alter table public.click_events
  add column if not exists visitor_id uuid,
  add column if not exists ip_address inet,
  add column if not exists city text,
  add column if not exists region text,
  add column if not exists country text,
  add column if not exists traffic_type text not null default 'human',
  add column if not exists bot_name text,
  add column if not exists user_agent text;

alter table public.click_events enable row level security;

create index if not exists click_events_created_at_idx
  on public.click_events (created_at desc);

create index if not exists click_events_event_type_idx
  on public.click_events (event_type, created_at desc);

create index if not exists click_events_page_path_idx
  on public.click_events (page_path, created_at desc);

create index if not exists click_events_session_id_idx
  on public.click_events (session_id, created_at desc);

create index if not exists click_events_visitor_id_idx
  on public.click_events (visitor_id, created_at desc);

create index if not exists click_events_country_city_idx
  on public.click_events (country, city, created_at desc);

create index if not exists click_events_traffic_type_idx
  on public.click_events (traffic_type, created_at desc);

comment on table public.click_events is
  'Website page-view and click analytics with anonymous visitor/session IDs, server-derived approximate location, and server-side traffic classification.';
